//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcOtopark.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLAracSeri
    {
        public int ID { get; set; }
        public Nullable<int> MarkaID { get; set; }
        public Nullable<int> Seri { get; set; }
    
        public virtual TBLAracMarka TBLAracMarka { get; set; }
    }
}
