//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcOtopark.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLParkBilgileri
    {
        public int ID { get; set; }
        public int MusteriID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Telefon { get; set; }
        public int MarkaID { get; set; }
        public int SeriID { get; set; }
        public string Model { get; set; }
        public string Renk { get; set; }
        public string Plaka { get; set; }
        public Nullable<System.DateTime> Yil { get; set; }
        public int ParkYeriID { get; set; }
        public Nullable<System.DateTime> GirisTarihi { get; set; }
        public Nullable<System.DateTime> CikisTarihi { get; set; }
    }
}
